version: 2
jobs:
  build_9_0_ccl_amd64:
    docker:
      - image: "love5an/dotnet-core-sdk-common-lisp:9.0-ccl-latest-noble"
    working_directory: ~/quicklisp/local-projects/bike
    steps:
      - checkout
      - run:
          name: Run tests
          command: cat tests.lisp | ccl64 -Q -b

  build_9_0_sbcl_amd64:
    docker:
      - image: "love5an/dotnet-core-sdk-common-lisp:9.0-sbcl-latest-noble"
    working_directory: ~/quicklisp/local-projects/bike
    steps:
      - checkout
      - run:
          name: Run tests
          command: cat tests.lisp | sbcl --disable-debugger --noprint

workflows:
  version: 2

  tests:
    jobs:
      - build_9_0_ccl_amd64
      - build_9_0_sbcl_amd64
